import "@radix-ui/themes/styles.css";
import "../tailwind.config";
import { Theme, ThemePanel } from "@radix-ui/themes";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Header";
import Provider from "./auth/Provider";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Provider>
        <Theme appearance="light" accentColor="tomato">
          <Header />
          <main className="p-5 w-[80%] mx-auto">{children}</main>
        </Theme>
        </Provider>
      </body>
    </html>
  );
}
